---
root: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  node: true
  mocha: true
  browser: true
  es6: true
rules:
  block-scoped-var: error
  brace-style:
    - error
    - stroustrup
  camelcase: off
  consistent-return: error
  curly:
    - error
    - all
  comma-dangle:
    - error
    - always-multiline
  dot-notation:
    - error
    -
      allowKeywords: true
  eqeqeq:
    - error
    - allow-null
  space-before-blocks: error
  strict: off
  new-cap: error
  no-bitwise: error
  no-caller: error
  no-case-declarations: off
  no-cond-assign:
    - error
    - except-parens
  no-debugger: error
  no-empty: error
  no-eval: error
  no-extend-native: error
  no-irregular-whitespace: error
  no-iterator: error
  no-loop-func: error
  no-multi-str: error
  no-new: error
  no-plusplus: error
  no-proto: error
  no-script-url: error
  no-sequences: error
  no-undef: error
  no-unused-vars:
    - error
    - args: none
  no-with: error
  one-var:
    - error
    - never
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always
  valid-typeof: error
  wrap-iife:
    - error
    - inside
  array-bracket-spacing:
    - error
    - always
    -
      objectsInArrays: false
      arraysInArrays: false

  no-warning-comments: warn
  no-console: warn

  no-var: error
  arrow-spacing: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  template-curly-spacing: error


  react/no-typos: error
  react/no-string-refs: error
  react/no-unknown-property: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/self-closing-comp: error
  react/sort-comp: error
  react/style-prop-object: error
  react/void-dom-elements-no-children: error
  react/jsx-key: error
  react/jsx-pascal-case: error
  react/jsx-no-duplicate-props: error
  react/jsx-closing-bracket-location: error
  react/jsx-closing-tag-location: error
  react/jsx-curly-spacing: error
  react/jsx-equals-spacing: error
  react/jsx-tag-spacing: error
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-wrap-multilines:
    - error
    -
      declaration: parens-new-line
      assignment: parens-new-line
      return: parens-new-line
      arrow: parens-new-line
      condition: parens-new-line
      logical: parens-new-line
      prop: parens-new-line
